### ISSUE TITLE
Only the first media query is used

### ISSUE THREAD

**Issue by redhorn** [jonkemp/mediaquery-text#2]
`queryString.push(os.EOL + '@media ' + query.media[0] + ' {');`

If multiple comma separated media queries are specified, only the first one is used.

For example:

`@media (-webkit-min-device-pixel-ratio 0), (min--moz-device-pixel-ratio: 0) {`

results in:

`@media (-webkit-min-device-pixel-ratio 0) {`

Fix:

`var queryMedia = Array.prototype.slice.call(query.media).join(', ')`
`...`
`queryString.push(os.EOL + '@media ' + queryMedia + ' {');`

**Comment by jonkemp** [comment]
Pull request is here: https://github.com/jonkemp/mediaquery-text/pull/3

**Comment by jonkemp** [comment]
Pull request merged.
